sudo: false
language: node_js
node_js:
- '10'
matrix:
  fast_finish: true
  allow_failures: []
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/1ec050bc004d0e2161cb5286c247850d24aecc02/scripts/node-publish.bash)"
notifications:
  slack:
    secure: cW6+MF/MCzh2WIdw5e22zng6kTwOVoKFC0bOdy+G8kbF5264ACL80SlIhPMAL7Bo6QBHJlArES448bBa/zNK9s613gscZMADRW6lXQbV2rHt5FBrQxZNJDM6NVsayelJF0BTMLVvSvfHD2XiWr1xMEHbvhrqlWEuARP5KiHR2SfCNsK1PP4bdTasVhofSWu79W3h/GQvPp//dRSvKFLg6Vuvv3d082+PrkmG8rOuB5aFX0gz2d5IQcoGegtHDaDWc0C7sSBPsy7fKmwJH7ljV7DYuZmt42lPumxN7j/Ib7J1uvob6BqhXlUlI6zPyC6YUMGnYOTjwV7ZUCloQfS5qnv1kx2Y/1FTICud9mnz7flQdnandFK4kLK8QK9Vs2JvryeB/k37HL2vvW8N8QbxE8GMkUolwKQnWJf2Huz0k6Ct1IoriY8rlaUT65qTF/z+ssyNwTf0uMRTYATtBzA9hekV+4yX2+Iq43mNJQM318ShYA9tk7mCeBc83Nh0x7GZDWBXZBn0zP+TVg0DBKqui4yNibQrbBoaK9VoGu0SlZXkA15pEUcRrbw0mreqxhy/QETmUXlzwfIUtsTOrIBolJ2fE7JBWte6OufyZR383WOp+AGyz1FGKENKbWtCFr//cLh0Ofh1W/BMFLp+Z46Su9wxB/AkbCFNANTlkV4OAi0=
  email:
    recipients:
      secure: XnwpVm7cwAr8PrhEi5jIKSmAJJizahZMI6SdipEdd8kXl6Q2Z1enpI8MDEsJV4yJOIUXRo6Lg2pR6btMppxE3PNgCdT5e6TTe5cUhQ/90TFK73jZkp1lnVeJ+oZXj8SODoQ3wF7rU2d1Awfj/EoZSufUDKz6zGWxQEgGzeQNpKkHLfiuSPZNq5C8u/MHaCelSEPaiFPo/v5QYx3FQpMt3SNLBtBxpExoHn/f3EaaCQmzO3tjrVYH7W+Hs3bF7wPshl3y+mXsSRHJstSLkRKEQ4xP1xuAInpiFf6NHXfgba49heWLwZ8OdeyqxIqXljqkVnc1iPFwd8uGs5SnxxFp4OTdanXfoXQhyz5int8VqCQJ+IpX1F39uOLUjZlOQzJVEjMJislJlUEyVlIWBmcRp7xMWImguiwyWZFZd+lHKf0zRMPlzY3LBLAS1boS14MbWp4aio+72kUlY7CjzCJCWYIHt+FZAFboJL2dGWYEEFVcUltsbS97KbJ76rPKClzdpMjpTPGRSHcp51ZXGbCsr46yNE3XQiNuGd6macP8Q85LUb8aauATU018X60Q7jEjV1/ImbyV/5Aqpm0Qum1TKdn1ZULTwP65+Vucqp1I+ENAhGvTYQM2VaGOiyGutozahzIyuC/zIjSF/H4xaSBXXfkpkYVbPVd8Z29zCqKffN8=
